Repository jojoDevs/Omokat-FE, pull requests merged in 2022-11, with the labels that each got.

#1 11/5 로그인페이지 스타일 구현
  public/index.html
  src/App.css
  src/App.tsx
  src/assets/icons/kakao.svg
  src/assets/logo/logo.svg
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Inputs.tsx
  src/components/logInPage/LogInButtons.tsx
  src/components/logInPage/LogInForm.tsx
  src/components/logInPage/styles/logInButtons.module.scss
  src/components/logInPage/styles/logInForm.module.scss
  src/index.css
  src/pages/EndingPage.tsx
  src/pages/FindIdPage.tsx
  src/pages/FindPwdPage.tsx
  src/pages/LogInPage.tsx
  src/pages/MainPage.tsx
  src/pages/OmokPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/UserPage.tsx
  src/pages/styles/logInPage.module.scss
  src/shared/styles/buttons.scss
  src/shared/styles/colors.scss
  src/shared/styles/inputs.scss
Labels: 로그인

#2 11/7 스타일 구현
  src/assets/icons/default_profile.svg
  src/assets/logo/logo_black.svg
  src/components/common/Header.tsx
  src/components/signUpPage/SignUpButtons.tsx
  src/components/signUpPage/SignUpForm.tsx
  src/components/signUpPage/styles/signUpButtons.module.scss
  src/components/signUpPage/styles/signUpForm.module.scss
  src/pages/SignUpPage.tsx
  src/pages/styles/signUpPage.module.scss
  src/shared/styles/buttons.scss
  src/shared/styles/colors.scss
  src/shared/styles/header.scss
  src/shared/styles/inputs.scss
  src/shared/styles/mixins.scss
Labels: attention!, 회원가입

#3 11/7 공통 스타일 변경 적용
  src/components/logInPage/LogInButtons.tsx
  src/components/logInPage/LogInForm.tsx
  src/components/logInPage/styles/logInButtons.module.scss
  src/components/logInPage/styles/logInForm.module.scss
  src/pages/LogInPage.tsx
  src/pages/styles/logInPage.module.scss
Labels: 로그인

#4 11/7 헤더 스타일 수정
  src/components/common/Header.tsx
  src/shared/styles/header.scss
Labels: attention!

#6 11/7 스타일 구현 및 수정
  src/assets/logo/logo_gray.svg
  src/components/common/Footer.tsx
  src/components/signUpPage/SignUpForm.tsx
  src/components/signUpPage/styles/signUpForm.module.scss
  src/pages/styles/signUpPage.module.scss
  src/shared/styles/footer.scss
Labels: attention!, 회원가입

#7 11/8 메인 스타일 구현 & 공통 mixins 변경
  src/App.tsx
  src/assets/icons/more.svg
  src/components/findIdPage/styles/findIdButton.module.scss
  src/components/findPwdPage/styles/findPwdButton.module.scss
  src/components/findPwdPage/styles/findPwdForm.module.scss
  src/components/mainPage/Banner.tsx
  src/components/mainPage/Card.tsx
  src/components/mainPage/MainButtons.tsx
  src/components/mainPage/RoomCards.tsx
  src/components/mainPage/styles/banner.module.scss
  src/components/mainPage/styles/card.module.scss
  src/components/mainPage/styles/mainButtons.module.scss
  src/components/mainPage/styles/roomCards.module.scss
  src/pages/MainPage.tsx
  src/pages/styles/findIdPage.module.scss
  src/pages/styles/findPwdPage.module.scss
  src/pages/styles/logInPage.module.scss
  src/shared/styles/mixins.scss
Labels: attention!, 메인

#10 11/9 헤더, footer 스타일 수정
  src/shared/styles/footer.scss
  src/shared/styles/header.scss
Labels: attention!

#11 11/9 로그인 스타일 수정
  src/components/logInPage/styles/logInButtons.module.scss
  src/components/logInPage/styles/logInForm.module.scss
  src/pages/styles/logInPage.module.scss
Labels: 로그인

#12 11/9 메인 반응형 적용
  src/components/mainPage/Card.tsx
  src/components/mainPage/MainButtons.tsx
  src/components/mainPage/styles/card.module.scss
  src/components/mainPage/styles/mainButtons.module.scss
  src/components/mainPage/styles/roomCards.module.scss
Labels: 메인

#13 11/9 스타일 구현 및 수정
  src/App.tsx
  src/assets/cats/ending/calico.svg
  src/assets/cats/ending/cheese.svg
  src/assets/cats/ending/graycat.svg
  src/assets/cats/ending/king.svg
  src/assets/cats/ending/lion.svg
  src/assets/cats/ending/persian.svg
  src/assets/cats/ending/ragdoll.svg
  src/assets/cats/ending/rudolph.svg
  src/assets/cats/ending/siamese.svg
  src/assets/cats/ending/tuxedo.svg
  src/assets/icons/box.svg
  src/assets/icons/box_open.svg
  src/components/endingPage/CatItem.tsx
  src/components/endingPage/ChooseBox.tsx
  src/components/endingPage/ClosedBox.tsx
  src/components/endingPage/EndingButton.tsx
  src/components/endingPage/EndingContent.tsx
  src/components/endingPage/EndingTexts.tsx
  src/components/endingPage/GetItem.tsx
  src/components/endingPage/styles/chooseBox.module.scss
  src/components/endingPage/styles/closedBox.module.scss
  src/components/endingPage/styles/endingButton.module.scss
  src/components/endingPage/styles/endingItem.module.scss
  src/components/endingPage/styles/endingTexts.module.scss
  src/components/endingPage/styles/getItem.module.scss
  src/components/signUpPage/SignUpForm.tsx
  src/components/signUpPage/styles/signUpForm.module.scss
  src/pages/EndingPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/styles/endingPage.module.scss
  src/pages/styles/signUpPage.module.scss
  src/shared/styles/header.scss
Labels: attention!, 회원가입, 오목완료

#14 11/9 메인 반응형 수정
  src/components/mainPage/Card.tsx
  src/components/mainPage/styles/card.module.scss
Labels: 메인

#15 11/9 헤더 스타일 수정
  src/shared/styles/header.scss
Labels: attention!

#16 11/13 초기 설정 값 변경 및 공통 axios api, instance 추가 작업
  .gitignore
  src/shared/routes/apis.ts
  src/shared/routes/instance.ts
  tsconfig.json
Labels: attention!

#17 11/13 스타일 모듈화
  src/components/common/Background.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/LogoTitle.tsx
  src/components/common/styles/background.module.scss
  src/components/common/styles/footer.module.scss
  src/components/common/styles/header.module.scss
  src/components/common/styles/logoTitle.module.scss
Labels: attention!

#18 11/13 패키지 설치 및 회원가입 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Inputs.tsx
  src/components/signUpPage/SignUpButtons.tsx
  src/components/signUpPage/SignUpForm.tsx
  src/components/signUpPage/styles/signUpForm.module.scss
  src/hooks/query/usePostSignUp.ts
  src/index.tsx
  src/redux/modules/userSlice.ts
  src/redux/store.ts
  src/shared/routes/instance.ts
  src/types/userType.ts
Labels: attention!, 회원가입

#19 11/14 로그인 기능 개발 및 instance 토큰 코드 수정
  src/components/common/Inputs.tsx
  src/components/logInPage/LogInButtons.tsx
  src/components/logInPage/LogInForm.tsx
  src/hooks/query/usePostLogIn.ts
  src/pages/LogInPage.tsx
  src/redux/modules/userSlice.ts
  src/shared/routes/apis.ts
  src/shared/routes/instance.ts
  src/types/userType.ts
Labels: attention!, 로그인

#20 11/14 계정찾기 기능 & useScroll 커스텀 훅 개발
  src/App.tsx
  src/components/common/Inputs.tsx
  src/components/findIdPage/FindIdButton.tsx
  src/components/findIdPage/FindIdForm.tsx
  src/components/findPwdPage/FindPwdButton.tsx
  src/components/findPwdPage/FindPwdForm.tsx
  src/components/findPwdPage/styles/findPwdButton.module.scss
  src/components/findPwdPage/styles/findPwdForm.module.scss
  src/components/signUpPage/SignUpButtons.tsx
  src/hooks/query/usePostFindId.ts
  src/hooks/query/usePostFindPwd.ts
  src/hooks/query/usePostLogIn.ts
  src/hooks/query/usePutResetPwd.ts
  src/hooks/useScroll.ts
  src/pages/FindIdPage.tsx
  src/pages/FindPwdPage.tsx
  src/pages/LogInPage.tsx
  src/pages/SignUpPage.tsx
  src/redux/modules/userSlice.ts
  src/shared/routes/apis.ts
  src/types/userType.ts
Labels: attention!, 계정찾기

#21 11/14 로그인 시 프로필 이미지 저장
  src/hooks/query/usePostLogIn.ts
Labels: 로그인

#22 11/15 유저 기능 구현
  package-lock.json
  package.json
  src/assets/cats/ending/cheese.svg
  src/assets/cats/ending/graycat.svg
  src/assets/cats/ending/king.svg
  src/assets/cats/ending/lion.svg
  src/assets/cats/ending/persian.svg
  src/assets/cats/ending/ragdoll.svg
  src/assets/cats/ending/rudolph.svg
  src/assets/cats/ending/siamese.svg
  src/assets/cats/ending/tuxedo.svg
  src/assets/icons/upload.svg
  src/components/common/Header.tsx
  src/components/common/styles/header.module.scss
  src/components/userPage/UserButtons.tsx
  src/components/userPage/UserProfile.tsx
  src/components/userPage/styles/userButtons.module.scss
  src/components/userPage/styles/userProfile.module.scss
  src/hooks/query/useGetUser.ts
  src/hooks/query/usePutUserPic.ts
  src/pages/UserPage.tsx
  src/shared/routes/apis.ts
  src/utils/cats.ts
Labels: attention!, 유저
